# Generated by Django 5.1.2 on 2024-10-28 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='F.I.Sh')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('user', 'Oddiy foydalanuvchi')], default='user', max_length=100, null=True, verbose_name='Foydalanuvchi roli')),
                ('joined_at', models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 28, 12, 37, 56, 306498), null=True, verbose_name="Qo'shilgan vaqti")),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
            },
        ),
    ]
